force-app/main/default/objects/Floor__c/Floor__c.object-meta.xml
<CustomObject>
    <label>Floor</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Floors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Floor__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Floors</relationshipLabel>
    <relationshipName>Floors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/No_Of_Floors__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Floors__c</fullName>
    <label>No Of Floors</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TowerTriggerHelper.cls
public class TowerTriggerHelper {
    public static void createFloorHelper(Id id, Decimal floorNum){
        
        List<Floor__c> tobeinserted = new List<Floor__c>();
        
        for(Integer i = 1 ;i<=floorNum && floorNum<150;i++){
            Floor__c  f = new Floor__c();
           // Integer numoff = i+1;
            f.Name = 'Floor '+ i ;
            f.Tower__c = id;
            tobeinserted.add(f);
        }
        
        if(tobeinserted.size()>0){
            insert tobeinserted;
        }

    }
	
    public static void createFloors(List<Tower__c> list_of_towers){
        
        List<Floor__c> fl = new List<Floor__c>();
       	Map<Id,Decimal> floor_on_tower = new Map<Id,Decimal>();
        for(Tower__c eachTower : list_of_towers){
            floor_on_tower.put(eachTower.Id, eachTower.No_Of_Floors__c);
        }
        
         for (Id id: floor_on_tower.keySet()){
			createFloorHelper(id,floor_on_tower.get(id));
            
        }
      	  
    }
}